# -*- coding: utf-8 -*-
"""10-05-24-CorrKard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PsD_GMuEz3F4OIO9L8_KmcwaBruUYCBw
"""

import numpy as np

# Definindo o número de corredores e voltas
num_corredores = 6
num_voltas = 10

# Criando listas para armazenar os nomes dos corredores e os tempos de cada volta
nomes_corredores = [(2,4,6,8,10,12)]
tempos_corredores = [(60)]

# Solicitando os nomes dos corredores
for i in range(num_corredores):
    nome = input("Digite o nome do corredor {}: ".format(i+1))
    nomes_corredores.append(nome)



# Solicitando os tempos das voltas para cada corredor
for i in range(num_corredores):
    tempos_corredor = []
    print("\nDigite os tempos das 10 voltas para o corredor", nomes_corredores[i])
    for j in range(num_voltas):
        tempo_volta = float(input("Tempo da volta {} (segundos): ".format(j+1)))
        tempos_corredor.append(tempo_volta)
    tempos_corredores.append(tempos_corredor)

# Melhor volta da prova
menor_tempo = np.min(tempos_corredores)
indice_corredor, indice_volta = np.where(tempos_corredores == menor_tempo)
melhor_volta_corredor = nomes_corredores[indice_corredor[0]]
melhor_volta_volta = indice_volta[0] + 1

print("\nMelhor volta da prova:")
print("Corredor:", melhor_volta_corredor)
print("Volta:", melhor_volta_volta)
print("Tempo:", menor_tempo, "segundos")

# Classificação final em ordem crescente
media_tempos_corredores = np.mean(tempos_corredores, axis=1)
classificacao_final = sorted(zip(nomes_corredores, media_tempos_corredores), key=lambda x: x[1])

print("\nClassificação final em ordem crescente:")
for i, (corredor, media_tempo) in enumerate(classificacao_final, 1):
    print("{}º lugar: {} - Média de tempo: {:.2f} segundos".format(i, corredor, media_tempo))

# Volta com a média mais rápida
media_por_volta = np.mean(tempos_corredores, axis=0)
volta_media_mais_rapida = np.argmin(media_por_volta) + 1
media_tempo_volta_rapida = np.min(media_por_volta)

print("\nVolta com a média mais rápida:")
print("Volta:", volta_media_mais_rapida)
print("Média de tempo:", media_tempo_volta_rapida, "segundos")